### ISSUE TITLE
InputNorm the running sum of square computation is incorrect

### ISSUE THREAD

**Issue by Theomat** [entity-neural-network/incubator#32]
Merged with #30 in `ppo/train.py` the following code to update the sum of squares for a batch
```python
            # This is probably not quite right because it applies multiple updates simultaneously.
            self.squares_sum = self.squares_sum + (
                (input - self.mean) * (input - new_mean)
            ).sum(dim=0)
``` 
does not compute the correct sum of squares based on the formulas of [Welford's method](https://www.johndcook.com/blog/standard_deviation/)

**Comment by cswinter** [comment]
Full current code:

```python
self.count += count
new_mean = self.mean + (mean - self.mean) * count / self.count
# This is probably not quite right because it applies multiple updates simultaneously.
self.squares_sum = self.squares_sum + (
    (input - self.mean) * (input - new_mean)
).sum(dim=0)
self.mean = new_mean
```

I think the most correct code would be something like this:

```python
for i in input:
  self.count += 1
  new_mean = self.mean + (mean - self.mean) / self.count
  self.squares_sum += (i - self.mean) * (i - new_mean)
  self.mean = new_mean
```

The difference here is that we update the mean in between the summation terms. Since the mean will change increasingly slowly, I think the current implementation still converges to the correct value but may do so somewhat more slowly initially.
